In [ ]:
pip install tensorflow

In [ ]:
import tensorflow as tf
import numpy as np
print("tensor version: ", tf.__version__)

tensor version:  2.19.0


In [ ]:
# Scalar tensor
scalar = tf.constant(10) # --- scaler value ---
print(scalar)

tf.Tensor(10, shape=(), dtype=int32)


In [ ]:
# 1D tensor -- Vector tensor
vector = tf.constant([1, 2, 3, 4]) # --- vector values ---
print(vector)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [ ]:
# 2D Tensor -- Matrix tensor
matrix = tf.constant([[1, 2], [3, 4]]) # --- matrix values ---
print(matrix)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
#Operations on Scalar Tensor

a = tf.constant(10)
b = tf.constant(5)
print("Addition:", tf.add(a, b))
print("Subtraction:", tf.subtract(a, b))
print("Multiplication:", tf.multiply(a, b))
print("Division:", tf.divide(a, b))

Addition: tf.Tensor(15, shape=(), dtype=int32)
Subtraction: tf.Tensor(5, shape=(), dtype=int32)
Multiplication: tf.Tensor(50, shape=(), dtype=int32)
Division: tf.Tensor(2.0, shape=(), dtype=float64)


In [ ]:
# Operations on  Vector Tensor

a = tf.constant([10, 20, 30])
b = tf.constant([1, 2, 3])

print("Addition:", tf.add(a, b))
print("Subtraction:", tf.subtract(a, b))
print("Multiplication:", tf.multiply(a, b))
print("Division:", tf.divide(a, b))

Addition: tf.Tensor([11 22 33], shape=(3,), dtype=int32)
Subtraction: tf.Tensor([ 9 18 27], shape=(3,), dtype=int32)
Multiplication: tf.Tensor([10 40 90], shape=(3,), dtype=int32)
Division: tf.Tensor([10. 10. 10.], shape=(3,), dtype=float64)


In [ ]:
# Operations on Matrix Tensor
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

print("Addition:", tf.add(a, b))
print("Subtraction:", tf.subtract(a, b))
print("Multiplication:", tf.multiply(a, b))
print("Division:", tf.divide(a, b))

Addition: tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Subtraction: tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)
Multiplication: tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
Division: tf.Tensor(
[[0.2        0.33333333]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float64)


In [ ]:
#Data Types and Shape of Tensors

tensor = tf.constant([[1, 2, 3], [4, 5, 6]])

print("Data Type:", tensor.dtype)
print("Shape:", tensor.shape)
print("Number of Dimensions:", tf.rank(tensor)) # rank of matrix
print("Number of Dimensions:", tensor.ndim) # dimensions of matrix

Data Type: <dtype: 'int32'>
Shape: (2, 3)
Number of Dimensions: tf.Tensor(2, shape=(), dtype=int32)
Number of Dimensions: 2


In [ ]:
#Converting NumPy Arrays to Tensors

numpy_array = np.array([[1, 2, 3], [4, 5, 6]])

tensor = tf.convert_to_tensor(numpy_array)

print("NumPy Array:\n", numpy_array) #numpy array
print("TensorFlow Tensor:\n", tensor) #tensorflow tensor

NumPy Array:
 [[1 2 3]
 [4 5 6]]
TensorFlow Tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)
